import { Destination, Tour } from "@travel-and-tour/db";
import { Router, type Router as ExpressRouter } from "express";

const router: ExpressRouter = Router();

const IMG = (seed: string) =>
  `https://picsum.photos/seed/${seed}/1200/800`;

const daysFromNow = (days: number) => {
  const date = new Date();
  date.setUTCDate(date.getUTCDate() + days);
  date.setUTCHours(12, 0, 0, 0);
  return date;
};

const DATES = [17, 36, 53, 72, 92, 130].map(daysFromNow);

const slots = (total: number) =>
  DATES.map((date) => ({ date, totalSpots: total, bookedSpots: 0 }));

router.post("/", async (_req, res) => {
  await Tour.deleteMany({});
  await Destination.deleteMany({});

  const destinations = await Destination.insertMany([
    {
      name: "Bali",
      country: "Indonesia",
      description:
        "A spiritual island paradise of terraced rice fields, ancient temples, volcanic mountains, and world-class beaches.",
      coverImage: IMG("bali-temple-sunset"),
      images: [IMG("bali-rice-terraces"), IMG("bali-beach"), IMG("bali-volcano"), IMG("bali-ceremony"), IMG("bali-ubud")],
      popular: true,
      climate: "Tropical",
      bestTimeToVisit: "April – October",
      tourCount: 3,
    },
    {
      name: "Paris",
      country: "France",
      description:
        "The City of Light dazzles with iconic landmarks, world-class cuisine, and an unparalleled arts and culture scene.",
      coverImage: IMG("paris-eiffel-tower"),
      images: [IMG("paris-seine-river"), IMG("paris-louvre"), IMG("paris-montmartre"), IMG("paris-cafe")],
      popular: true,
      climate: "Temperate",
      bestTimeToVisit: "April – June, September – November",
      tourCount: 1,
    },
    {
      name: "Machu Picchu",
      country: "Peru",
      description:
        "Explore the legendary 15th-century Inca citadel perched high in the Andes, surrounded by breathtaking cloud forests.",
      coverImage: IMG("machu-picchu-citadel"),
      images: [IMG("inca-trail-trek"), IMG("andes-mountains"), IMG("cusco-peru"), IMG("machu-picchu-sunrise")],
      popular: true,
      climate: "Highland Tropical",
      bestTimeToVisit: "May – September",
      tourCount: 2,
    },
    {
      name: "Serengeti",
      country: "Tanzania",
      description:
        "Witness one of nature's greatest spectacles — the Great Migration — across Africa's most iconic wildlife wilderness.",
      coverImage: IMG("serengeti-safari-sunset"),
      images: [IMG("serengeti-wildebeest"), IMG("africa-elephant"), IMG("safari-lion"), IMG("serengeti-balloon")],
      popular: true,
      climate: "Semi-arid",
      bestTimeToVisit: "June – October",
      tourCount: 1,
    },
    {
      name: "Santorini",
      country: "Greece",
      description:
        "Famous for its white-washed clifftop villages, volcanic beaches, and stunning Aegean sunsets.",
      coverImage: IMG("santorini-white-buildings"),
      images: [IMG("santorini-caldera-view"), IMG("santorini-blue-dome"), IMG("santorini-oia-sunset"), IMG("santorini-sea")],
      popular: true,
      climate: "Mediterranean",
      bestTimeToVisit: "April – November",
      tourCount: 1,
    },
    {
      name: "Iceland",
      country: "Iceland",
      description:
        "A land of fire and ice — geysers, glaciers, volcanoes, waterfalls, and magical northern lights await.",
      coverImage: IMG("iceland-northern-lights"),
      images: [IMG("iceland-waterfall"), IMG("iceland-glacier"), IMG("iceland-geyser"), IMG("iceland-black-beach")],
      popular: false,
      climate: "Subarctic",
      bestTimeToVisit: "June – August (Midnight Sun), September – March (Northern Lights)",
      tourCount: 1,
    },
    {
      name: "Tokyo",
      country: "Japan",
      description:
        "A city where ancient temples meet neon-lit skyscrapers — world-class sushi, cherry blossoms, hidden izakayas, and the most efficient city on earth.",
      coverImage: IMG("tokyo-skyline-night"),
      images: [IMG("tokyo-shibuya-crossing"), IMG("tokyo-temple-shrine"), IMG("japan-cherry-blossom"), IMG("tokyo-ramen")],
      popular: true,
      climate: "Temperate",
      bestTimeToVisit: "March – May (Cherry Blossom), October – November",
      tourCount: 1,
    },
    {
      name: "Amalfi Coast",
      country: "Italy",
      description:
        "Dramatic cliffs tumbling into turquoise seas, pastel villages clinging to hillsides, and Italy's finest seafood, limoncello, and la dolce vita.",
      coverImage: IMG("amalfi-coast-cliffs"),
      images: [IMG("positano-village"), IMG("capri-island"), IMG("cinque-terre-coast"), IMG("italy-mediterranean")],
      popular: true,
      climate: "Mediterranean",
      bestTimeToVisit: "April – June, September – October",
      tourCount: 1,
    },
    {
      name: "Marrakech",
      country: "Morocco",
      description:
        "A sensory explosion of spice-scented souks, ornate riads, ancient medina walls, and the vast Sahara desert just beyond the city gates.",
      coverImage: IMG("marrakech-medina"),
      images: [IMG("morocco-souk"), IMG("sahara-desert-dunes"), IMG("marrakech-riad"), IMG("morocco-atlas")],
      popular: true,
      climate: "Semi-arid",
      bestTimeToVisit: "March – May, September – November",
      tourCount: 1,
    },
    {
      name: "Phuket",
      country: "Thailand",
      description:
        "Crystal-clear Andaman waters, limestone karsts rising from the sea, Buddhist temples, vibrant street food, and Asia's most stunning island beaches.",
      coverImage: IMG("phuket-andaman-sea"),
      images: [IMG("thailand-limestone-karst"), IMG("phi-phi-islands"), IMG("thailand-beach-resort"), IMG("phuket-temple")],
      popular: true,
      climate: "Tropical",
      bestTimeToVisit: "November – April",
      tourCount: 1,
    },
  ]);

  const [bali, paris, machu, serengeti, santorini, iceland, tokyo, amalfi, marrakech, phuket] = destinations;

  await Tour.insertMany([
    {
      title: "Bali Cultural Immersion",
      slug: "bali-cultural-immersion",
      description:
        "Discover the spiritual heart of Bali through ancient temples, traditional ceremonies, rice terrace walks, and immersive village homestays led by local expert guides.",
      destination: "Bali",
      country: "Indonesia",
      price: 899,
      duration: 7,
      maxGroupSize: 12,
      difficulty: "easy",
      coverImage: IMG("bali-temple-sunset"),
      images: [IMG("bali-rice-terraces"), IMG("bali-ceremony"), IMG("bali-volcano"), IMG("bali-ubud")],
      highlights: [
        "Sunrise hike on Mount Batur volcano",
        "Visit to iconic Tanah Lot sea temple",
        "Traditional Balinese cooking class",
        "Tegallalang rice terrace trekking",
        "Sacred Monkey Forest sanctuary",
      ],
      itinerary: [
        { day: 1, title: "Arrival in Ubud", description: "Welcome ceremony at a traditional Balinese family compound, orientation walk through Ubud Market." },
        { day: 2, title: "Temples & Rice Terraces", description: "Morning visit to Tirta Empul holy springs, afternoon walk through Tegallalang rice terraces." },
        { day: 3, title: "Volcanic Sunrise", description: "Pre-dawn hike to the summit of Mount Batur for sunrise views over Lake Batur." },
        { day: 4, title: "Cooking & Crafts", description: "Traditional Balinese cooking class in the morning, silversmithing workshop in the afternoon." },
        { day: 5, title: "Sacred Temples", description: "Full day visiting Besakih (Mother Temple), Kehen Temple and the bat cave temple of Goa Lawah." },
        { day: 6, title: "Beach Day & Tanah Lot", description: "Free morning at Seminyak Beach, sunset visit to Tanah Lot sea temple." },
        { day: 7, title: "Departure", description: "Morning reflection, farewell breakfast, transfer to Ngurah Rai International Airport." },
      ],
      included: ["7 nights accommodation (4★ boutique hotels)", "Daily breakfast + 5 dinners", "All entrance fees and activities", "Expert English-speaking local guide", "Private air-conditioned transport"],
      notIncluded: ["International flights", "Travel insurance", "Personal expenses", "Lunch on most days", "Optional activities"],
      availability: slots(12),
      averageRating: 4.8,
      reviewCount: 124,
      featured: true,
      category: "cultural",
    },
    {
      title: "Paris Beyond the Postcard",
      slug: "paris-beyond-the-postcard",
      description:
        "Experience Paris like a local — hidden courtyards, artisan markets, café culture, and curated visits to the Louvre and Versailles with exclusive skip-the-line access.",
      destination: "Paris",
      country: "France",
      price: 1299,
      duration: 5,
      maxGroupSize: 10,
      difficulty: "easy",
      coverImage: IMG("paris-eiffel-tower"),
      images: [IMG("paris-louvre"), IMG("paris-versailles"), IMG("paris-montmartre")],
      highlights: [
        "Skip-the-line Louvre guided tour",
        "Private Eiffel Tower sunset experience",
        "Day trip to Palace of Versailles",
        "Hidden Marais neighbourhood food walk",
        "French patisserie and wine tasting",
      ],
      itinerary: [
        { day: 1, title: "Bienvenue à Paris", description: "Arrive at CDG, transfer to Saint-Germain hotel, evening Seine river cruise." },
        { day: 2, title: "The Louvre & Le Marais", description: "Skip-the-line Louvre tour (3 hrs), afternoon food walk through Le Marais district." },
        { day: 3, title: "Versailles", description: "Full day at the Palace and Gardens of Versailles with exclusive behind-the-scenes access." },
        { day: 4, title: "Montmartre & Eiffel", description: "Morning in bohemian Montmartre, patisserie class, private Eiffel Tower sunset visit." },
        { day: 5, title: "Departure", description: "Morning at leisure in the Latin Quarter, CDG transfer." },
      ],
      included: ["5 nights 4★ hotel in central Paris", "Daily breakfast + 3 dinners", "All museum entrance fees", "Skip-the-line access", "Metro passes", "Expert art historian guide"],
      notIncluded: ["International flights", "Travel insurance", "Lunches", "Personal shopping"],
      availability: slots(10),
      averageRating: 4.9,
      reviewCount: 89,
      featured: true,
      category: "city",
    },
    {
      title: "Inca Trail Trek to Machu Picchu",
      slug: "inca-trail-trek-machu-picchu",
      description:
        "Follow the ancient Inca footpath through cloud forests and mountain passes to reach the Sun Gate at dawn and descend into the mystical citadel of Machu Picchu.",
      destination: "Machu Picchu",
      country: "Peru",
      price: 899,
      duration: 4,
      maxGroupSize: 8,
      difficulty: "challenging",
      coverImage: IMG("machu-picchu-citadel"),
      images: [IMG("inca-trail-trek"), IMG("andes-mountains"), IMG("machu-picchu-sunrise")],
      highlights: [
        "Trek the classic 45km Inca Trail",
        "Sunrise through the Sun Gate",
        "Guided Machu Picchu citadel tour",
        "Andean cloud forest ecosystems",
        "Archaeological site of Wiñay Wayna",
      ],
      itinerary: [
        { day: 1, title: "Km 82 → Wayllabamba", description: "Start at kilometre 82, trek through the Sacred Valley, camp at Wayllabamba (3,000m)." },
        { day: 2, title: "Dead Woman's Pass", description: "The hardest day — climb to Warmiwañusca Pass (4,215m), descend to Pacaymayo camp." },
        { day: 3, title: "Wiñay Wayna", description: "Trek through cloud forest to the spectacular ruins of Wiñay Wayna, final camp." },
        { day: 4, title: "Sun Gate & Machu Picchu", description: "Pre-dawn walk to Inti Punku (Sun Gate) for sunrise over Machu Picchu, guided citadel tour, train to Cusco." },
      ],
      included: ["3 nights camping (all equipment)", "All meals on trail (Day 1 dinner – Day 4 lunch)", "Certified Inca Trail guide", "Porters (up to 7kg per trekker)", "Inca Trail and Machu Picchu entry permits", "Train Aguas Calientes – Cusco"],
      notIncluded: ["Flights to/from Cusco", "Hotel nights in Cusco before/after", "Travel insurance", "Tips for guides and porters", "Hot showers at campsites ($3-5)"],
      availability: slots(8),
      averageRating: 4.7,
      reviewCount: 203,
      featured: true,
      category: "adventure",
    },
    {
      title: "Great Serengeti Migration Safari",
      slug: "great-serengeti-migration-safari",
      description:
        "Witness the world's greatest wildlife spectacle — millions of wildebeest and zebra thundering across the Serengeti plains — from luxury tented camps at the heart of the action.",
      destination: "Serengeti",
      country: "Tanzania",
      price: 3499,
      duration: 8,
      maxGroupSize: 6,
      difficulty: "moderate",
      coverImage: IMG("serengeti-safari-sunset"),
      images: [IMG("serengeti-wildebeest"), IMG("africa-elephant"), IMG("safari-lion")],
      highlights: [
        "Daily game drives in open 4×4 vehicles",
        "Witness the Great Migration river crossings",
        "Visit Ngorongoro Crater (UNESCO)",
        "Hot air balloon safari at sunrise",
        "Luxury tented camp accommodation",
      ],
      itinerary: [
        { day: 1, title: "Arrival in Arusha", description: "Fly into Kilimanjaro International Airport, transfer to Arusha for pre-safari briefing." },
        { day: 2, title: "Ngorongoro Crater", description: "Full day exploring the Ngorongoro Crater floor — Big Five territory." },
        { day: 3, title: "Serengeti North", description: "Transfer into Northern Serengeti, afternoon game drive, luxury tented camp check-in." },
        { day: 4, title: "Migration River Crossings", description: "Full day positioned at the Mara River watching dramatic wildebeest crossings." },
        { day: 5, title: "Hot Air Balloon", description: "Sunrise hot air balloon safari over the Serengeti, champagne bush breakfast." },
        { day: 6, title: "Central Serengeti", description: "Drive through the Seronera Valley — the best year-round wildlife corridor." },
        { day: 7, title: "Tarangire National Park", description: "Giant baobab forests and large elephant herds at Tarangire." },
        { day: 8, title: "Departure", description: "Morning game drive, transfer to Kilimanjaro Airport for departure." },
      ],
      included: ["7 nights luxury tented camps (full board)", "All park fees and conservation levies", "All game drives in private 4×4 vehicles", "Hot air balloon safari + champagne breakfast", "Professional FGASA-certified guide", "Internal flight Arusha – Serengeti"],
      notIncluded: ["International flights to Kilimanjaro", "Travel insurance", "Visas", "Gratuities", "Alcoholic beverages", "Premium drinks at camps"],
      availability: slots(6),
      averageRating: 4.9,
      reviewCount: 67,
      featured: true,
      category: "wildlife",
    },
    {
      title: "Santorini Sunset Escape",
      slug: "santorini-sunset-escape",
      description:
        "Explore the iconic caldera villages of Oia and Fira, sail to volcanic hot springs, taste local wines in ancient vineyards, and watch the world-famous Santorini sunset.",
      destination: "Santorini",
      country: "Greece",
      price: 1899,
      duration: 6,
      maxGroupSize: 12,
      difficulty: "easy",
      coverImage: IMG("santorini-white-buildings"),
      images: [IMG("santorini-caldera-view"), IMG("santorini-blue-dome"), IMG("santorini-oia-sunset")],
      highlights: [
        "Private caldera sailing cruise",
        "Wine tasting at Santo Wines",
        "Sunset in Oia (best viewpoint on Earth)",
        "Swim in volcanic hot springs",
        "Archaeological site of Akrotiri",
      ],
      itinerary: [
        { day: 1, title: "Arrival in Fira", description: "Arrive at Santorini Airport, transfer to Fira, welcome Greek dinner with caldera views." },
        { day: 2, title: "Akrotiri & Red Beach", description: "Morning at Minoan ruins of Akrotiri, afternoon at iconic Red and White Beaches." },
        { day: 3, title: "Sailing Cruise", description: "Full-day private catamaran cruise around the caldera, hot springs, snorkelling, sunset BBQ on board." },
        { day: 4, title: "Wine & Villages", description: "Vineyard tour and wine tasting in Pyrgos, afternoon free in Imerovigli." },
        { day: 5, title: "Oia Exploration", description: "Morning walk along the caldera path to Oia, sunset from the famous castle ruins." },
        { day: 6, title: "Departure", description: "Leisurely morning, transfer to Santorini Airport." },
      ],
      included: ["6 nights 4★ boutique hotel with caldera view", "Daily breakfast + 3 dinners", "Private caldera sailing cruise", "Wine tasting experience", "All guided tours and entrance fees", "Airport transfers"],
      notIncluded: ["International flights", "Travel insurance", "Lunches", "Personal expenses", "Optional ATV rental"],
      availability: slots(12),
      averageRating: 4.8,
      reviewCount: 156,
      featured: false,
      category: "beach",
    },
    {
      title: "Iceland Northern Lights Adventure",
      slug: "iceland-northern-lights-adventure",
      description:
        "Chase the Aurora Borealis across Iceland's dramatic landscapes — geysers, glaciers, black sand beaches, and steaming hot springs — with expert guides who know where the lights dance.",
      destination: "Reykjavik",
      country: "Iceland",
      price: 2299,
      duration: 7,
      maxGroupSize: 10,
      difficulty: "moderate",
      coverImage: IMG("iceland-northern-lights"),
      images: [IMG("iceland-waterfall"), IMG("iceland-glacier"), IMG("iceland-geyser")],
      highlights: [
        "Nightly northern lights hunts",
        "Golden Circle: Geysir, Gullfoss, Þingvellir",
        "Glacier hike on Vatnajökull",
        "Jökulsárlón Glacier Lagoon boat tour",
        "Blue Lagoon geothermal spa",
      ],
      itinerary: [
        { day: 1, title: "Arrival in Reykjavik", description: "Arrive at Keflavik, orientation walk in colourful Reykjavik, first northern lights hunt." },
        { day: 2, title: "Golden Circle", description: "Full day on the Golden Circle: Þingvellir National Park, Geysir hot spring area, Gullfoss waterfall." },
        { day: 3, title: "South Coast", description: "Black sand beaches at Reynisfjara, Skógafoss and Seljalandsfoss waterfalls, northern lights." },
        { day: 4, title: "Glacier Lagoon", description: "Drive to Jökulsárlón, boat tour among floating icebergs, Diamond Beach." },
        { day: 5, title: "Glacier Hike", description: "Guided ice hike on the Vatnajökull glacier, ice caves exploration (seasonal)." },
        { day: 6, title: "Blue Lagoon", description: "Morning at leisure, afternoon soak at the iconic Blue Lagoon geothermal spa." },
        { day: 7, title: "Departure", description: "Transfer to Keflavik International Airport." },
      ],
      included: ["7 nights accommodation (mix of 3★ and 4★ hotels)", "Daily breakfast", "All guided activities and entrance fees", "Northern lights hunting excursions (3 nights)", "Blue Lagoon admission", "Glacier hike equipment", "Private minibus transport"],
      notIncluded: ["International flights", "Travel insurance", "Dinners (except Day 1)", "Personal expenses", "Tips"],
      availability: slots(10),
      averageRating: 4.7,
      reviewCount: 92,
      featured: false,
      category: "adventure",
    },
    {
      title: "Bali Surf & Yoga Retreat",
      slug: "bali-surf-yoga-retreat",
      description:
        "Find your balance in paradise — daily sunrise yoga sessions, learn to surf Bali's iconic waves at Canggu and Seminyak, and rejuvenate with traditional Balinese spa treatments.",
      destination: "Bali",
      country: "Indonesia",
      price: 1199,
      duration: 10,
      maxGroupSize: 8,
      difficulty: "easy",
      coverImage: IMG("bali-beach"),
      images: [IMG("bali-yoga-surf"), IMG("bali-canggu"), IMG("bali-temple-sunset")],
      highlights: [
        "Daily sunrise yoga and meditation",
        "Surfing lessons for all levels",
        "Traditional Balinese massage",
        "Organic Balinese cooking class",
        "Free time at Echo Beach, Canggu",
      ],
      itinerary: [
        { day: 1, title: "Arrival in Canggu", description: "Welcome ceremony, resort orientation, sunset yoga session on the beach." },
        { day: 2, title: "First Surf Lesson", description: "Morning yoga, beginner surfing lesson at Batu Bolong Beach, afternoon rest." },
        { day: 3, title: "Into the Flow", description: "Yoga, intermediate surf session, afternoon Balinese massage." },
        { day: 4, title: "Temple & Culture", description: "Morning yoga, optional surf, afternoon cultural excursion to Tanah Lot." },
        { day: 5, title: "Canggu Day", description: "Full yoga and surf day, explore the creative Canggu café scene." },
        { day: 6, title: "Seminyak Surf", description: "Transfer to Seminyak for advanced surf session, rooftop sunset yoga." },
        { day: 7, title: "Cooking Class", description: "Morning yoga, traditional Balinese cooking class, free evening." },
        { day: 8, title: "Ubud Day Trip", description: "Full day in Ubud — rice terraces, Monkey Forest, arts market." },
        { day: 9, title: "Final Surf", description: "Morning yoga, last surf session, farewell dinner on the beach." },
        { day: 10, title: "Departure", description: "Morning yoga at sunrise, transfer to Ngurah Rai Airport." },
      ],
      included: ["10 nights beachside boutique resort", "Daily breakfast + 6 dinners", "All yoga classes and surfboards/equipment", "2 Balinese massages", "Cooking class", "Ubud day trip with guide", "Airport transfers"],
      notIncluded: ["International flights", "Travel insurance", "Lunches", "Personal spa upgrades"],
      availability: slots(8),
      averageRating: 4.6,
      reviewCount: 78,
      featured: false,
      category: "beach",
    },
    {
      title: "Sacred Valley & Machu Picchu Explorer",
      slug: "sacred-valley-machu-picchu-explorer",
      description:
        "Journey through the heart of the Inca Empire — from the Pisac ruins and Ollantaytambo fortress to the Inca Trail and the breathtaking citadel of Machu Picchu.",
      destination: "Machu Picchu",
      country: "Peru",
      price: 1099,
      duration: 6,
      maxGroupSize: 12,
      difficulty: "moderate",
      coverImage: IMG("machu-picchu-sunrise"),
      images: [IMG("machu-picchu-citadel"), IMG("cusco-peru"), IMG("inca-trail-trek")],
      highlights: [
        "Sacred Valley: Pisac, Ollantaytambo, Moray",
        "Machu Picchu with certified archaeologist",
        "Scenic Vistadome train to Aguas Calientes",
        "Salt flats of Maras",
        "Traditional Andean village market",
      ],
      itinerary: [
        { day: 1, title: "Arrival in Cusco", description: "Arrive in Cusco, acclimatisation afternoon, welcome dinner in the Plaza de Armas." },
        { day: 2, title: "Cusco City Tour", description: "Morning tour of Qorikancha temple, Sacsayhuamán, and the historic city centre." },
        { day: 3, title: "Sacred Valley", description: "Full day Sacred Valley tour: Pisac ruins and market, Ollantaytambo fortress." },
        { day: 4, title: "Moray & Maras", description: "Visit the circular Inca agricultural terraces at Moray and the ancient Maras salt evaporation ponds." },
        { day: 5, title: "Machu Picchu", description: "Morning Vistadome train to Aguas Calientes, guided Machu Picchu tour — Sun Gate, Temple of the Sun, Intihuatana stone." },
        { day: 6, title: "Return & Departure", description: "Optional Huayna Picchu hike (early birds), afternoon train back to Cusco, departure." },
      ],
      included: ["6 nights hotels (3★ – 4★)", "Daily breakfast + 3 dinners", "All entrance fees (Cusco, Sacred Valley, Machu Picchu)", "Vistadome train tickets", "Expert archaeologist guide", "All transport"],
      notIncluded: ["Flights to/from Cusco", "Travel insurance", "Lunches", "Huayna Picchu/Machu Picchu Mountain surcharge", "Tips"],
      availability: slots(12),
      averageRating: 4.8,
      reviewCount: 115,
      featured: false,
      category: "cultural",
    },
    {
      title: "Tokyo Street Food & Culture",
      slug: "tokyo-street-food-culture",
      description:
        "Dive deep into Tokyo's layers — from Michelin-starred ramen alleys and teamLab digital art to ancient Shinto shrines, samurai history, and the buzzing nightlife of Shinjuku.",
      destination: "Tokyo",
      country: "Japan",
      price: 1599,
      duration: 7,
      maxGroupSize: 10,
      difficulty: "easy",
      coverImage: IMG("tokyo-skyline-night"),
      images: [IMG("tokyo-shibuya-crossing"), IMG("tokyo-temple-shrine"), IMG("japan-cherry-blossom")],
      highlights: [
        "Tsukiji outer market breakfast food tour",
        "teamLab Planets digital art experience",
        "Meiji Shrine and Harajuku street culture",
        "Shinjuku izakaya evening crawl",
        "Day trip to Nikko or Kamakura temples",
      ],
      itinerary: [
        { day: 1, title: "Arrival in Tokyo", description: "Transfer to hotel in Shinjuku, orientation walk, welcome dinner at a local izakaya." },
        { day: 2, title: "Traditional Tokyo", description: "Senso-ji Temple in Asakusa, Ueno museums, Akihabara electronics district." },
        { day: 3, title: "Food & Markets", description: "Tsukiji outer market breakfast, Toyosu fish market tour, Ginza lunch, Shibuya crossing." },
        { day: 4, title: "Art & Design", description: "teamLab Planets immersive art, Odaiba waterfront, Hamarikyu Gardens." },
        { day: 5, title: "Harajuku & Meiji", description: "Meiji Shrine, Harajuku Takeshita Street, Omotesando boutiques, Shinjuku evening." },
        { day: 6, title: "Day Trip", description: "Full day at Nikko UNESCO shrines and waterfalls, or Kamakura's Great Buddha." },
        { day: 7, title: "Departure", description: "Morning ramen breakfast, souvenir shopping in Nakameguro, Narita/Haneda transfer." },
      ],
      included: ["7 nights 3★ hotel in Shinjuku", "Daily breakfast + 3 dinners", "Suica metro card (7 days)", "All guided tours and entrance fees", "teamLab Planets ticket", "Day trip transport"],
      notIncluded: ["International flights", "Travel insurance", "Lunches", "Personal shopping", "Optional Michelin-starred dining"],
      availability: slots(10),
      averageRating: 4.8,
      reviewCount: 143,
      featured: true,
      category: "cultural",
    },
    {
      title: "Amalfi Coast & Cinque Terre Drive",
      slug: "amalfi-coast-cinque-terre-drive",
      description:
        "Cruise the world's most dramatic coastal road, island-hop to Capri, hike the Cinque Terre cliffs, and feast on fresh seafood and Campanian wine at every turn.",
      destination: "Amalfi Coast",
      country: "Italy",
      price: 1899,
      duration: 8,
      maxGroupSize: 10,
      difficulty: "moderate",
      coverImage: IMG("amalfi-coast-cliffs"),
      images: [IMG("positano-village"), IMG("capri-island"), IMG("cinque-terre-coast")],
      highlights: [
        "Private boat trip to Capri and Blue Grotto",
        "Hike the Path of the Gods (Sentiero degli Dei)",
        "Positano and Ravello village walks",
        "Cinque Terre coastal trail",
        "Limoncello and mozzarella tastings",
      ],
      itinerary: [
        { day: 1, title: "Arrival in Naples", description: "Transfer to Sorrento hotel, welcome dinner overlooking the Bay of Naples." },
        { day: 2, title: "Amalfi Drive", description: "Scenic coastal drive through Positano and Amalfi town, cliffside lunch with sea views." },
        { day: 3, title: "Capri by Boat", description: "Private boat to Capri, Blue Grotto, Villa San Michele, return by sunset." },
        { day: 4, title: "Ravello & Hiking", description: "Morning in Ravello's gardens, afternoon hike on the Path of the Gods." },
        { day: 5, title: "Pompeii", description: "Guided tour of Pompeii excavations, afternoon mozzarella farm visit." },
        { day: 6, title: "Travel to Cinque Terre", description: "Train north along the coast, check in to La Spezia, Vernazza evening stroll." },
        { day: 7, title: "Cinque Terre Trail", description: "Hike the coastal trail between the five villages, swim at Monterosso beach." },
        { day: 8, title: "Departure", description: "Morning espresso in Manarola, transfer to Pisa or Genoa airport." },
      ],
      included: ["8 nights boutique hotels", "Daily breakfast + 4 dinners", "Private boat to Capri", "Pompeii guided tour", "Cinque Terre hiking guide", "All train tickets on route"],
      notIncluded: ["International flights", "Travel insurance", "Lunches", "Blue Grotto entry (weather dependent)", "Personal expenses"],
      availability: slots(10),
      averageRating: 4.9,
      reviewCount: 88,
      featured: true,
      category: "beach",
    },
    {
      title: "Moroccan Imperial Cities & Sahara",
      slug: "moroccan-imperial-cities-sahara",
      description:
        "Wander ancient medinas in Fes and Marrakech, traverse the High Atlas mountains, ride camels into the Sahara at sunset, and sleep under a billion stars in a desert camp.",
      destination: "Marrakech",
      country: "Morocco",
      price: 1299,
      duration: 9,
      maxGroupSize: 12,
      difficulty: "moderate",
      coverImage: IMG("marrakech-medina"),
      images: [IMG("morocco-souk"), IMG("sahara-desert-dunes"), IMG("marrakech-riad")],
      highlights: [
        "Fes el-Bali medina — UNESCO World Heritage",
        "Camel trek into Erg Chebbi sand dunes",
        "Overnight desert camp under the stars",
        "Marrakech Djemaa el-Fna square",
        "Atlas Mountains Berber village visit",
      ],
      itinerary: [
        { day: 1, title: "Arrival in Casablanca", description: "Transfer to Rabat, visit Hassan Tower and Mohammed V Mausoleum, evening in the medina." },
        { day: 2, title: "Fes", description: "Drive to Fes, check in to a traditional riad, sunset views from the Merinid Tombs." },
        { day: 3, title: "Fes Medina", description: "Full day in Fes el-Bali — Chouara tanneries, Bou Inania madrasa, Al-Attarine souks." },
        { day: 4, title: "Sahara Road", description: "Drive via Ifrane and Ziz Valley to Merzouga, camel ride to desert camp." },
        { day: 5, title: "Desert Dawn", description: "Sunrise over the dunes, camel ride back, drive to Todra Gorge." },
        { day: 6, title: "High Atlas", description: "Dades Valley rose gorge, Aït Benhaddou UNESCO kasbah, mountain pass crossing." },
        { day: 7, title: "Marrakech Arrival", description: "Arrive in Marrakech, riad check-in, first exploration of Djemaa el-Fna at dusk." },
        { day: 8, title: "Marrakech Full Day", description: "Bahia Palace, Saadian Tombs, souks, cooking class in a traditional home." },
        { day: 9, title: "Departure", description: "Morning hammam spa, transfer to Marrakech Menara Airport." },
      ],
      included: ["9 nights (mix of riads and desert camp)", "Daily breakfast + 5 dinners", "Camel trek and overnight desert camp", "All guided medina tours", "Private driver throughout", "Cooking class"],
      notIncluded: ["International flights", "Travel insurance", "Lunches", "Hammam entry", "Tips for guides"],
      availability: slots(12),
      averageRating: 4.7,
      reviewCount: 96,
      featured: true,
      category: "adventure",
    },
    {
      title: "Thai Islands Escape",
      slug: "thai-islands-escape",
      description:
        "Island-hop through the Andaman's most spectacular scenery — sea kayak through limestone caves, snorkel pristine reefs, visit floating villages, and unwind on powdery white sand.",
      destination: "Phuket",
      country: "Thailand",
      price: 1199,
      duration: 8,
      maxGroupSize: 12,
      difficulty: "easy",
      coverImage: IMG("phuket-andaman-sea"),
      images: [IMG("thailand-limestone-karst"), IMG("phi-phi-islands"), IMG("thailand-beach-resort")],
      highlights: [
        "Phang Nga Bay sea kayaking",
        "Phi Phi Islands snorkelling",
        "James Bond Island (Ko Tapu)",
        "Elephant sanctuary visit (ethical)",
        "Traditional Thai cooking class",
      ],
      itinerary: [
        { day: 1, title: "Arrival in Phuket", description: "Transfer to Patong Beach hotel, welcome Thai dinner, evening stroll along Bangla Road." },
        { day: 2, title: "Phang Nga Bay", description: "Full-day speedboat tour — James Bond Island, sea kayaking through caves, Muslim floating village." },
        { day: 3, title: "Phi Phi Islands", description: "Speedboat to Ko Phi Phi, snorkelling at Maya Bay, Viking Cave, Bamboo Island." },
        { day: 4, title: "Elephant Sanctuary", description: "Morning at an ethical elephant sanctuary, afternoon Thai cooking class in the jungle." },
        { day: 5, title: "Ko Lanta", description: "Ferry to Ko Lanta, relax on uncrowded Klong Dao Beach, sunset over the Andaman." },
        { day: 6, title: "Koh Rok Snorkelling", description: "Longtail boat to Koh Rok marine park — world-class coral and crystal-clear waters." },
        { day: 7, title: "Ko Yao Yai", description: "Transfer to tranquil Ko Yao Yai, cycle rice paddies, long-tail boat to deserted beaches." },
        { day: 8, title: "Departure", description: "Return to Phuket, last Thai breakfast, transfer to Phuket International Airport." },
      ],
      included: ["8 nights (mix of beach resorts and island bungalows)", "Daily breakfast + 4 dinners", "All island boat trips", "Elephant sanctuary visit", "Cooking class", "All inter-island transfers"],
      notIncluded: ["International flights", "Travel insurance", "Lunches", "Alcoholic beverages", "Optional massage treatments"],
      availability: slots(12),
      averageRating: 4.8,
      reviewCount: 172,
      featured: false,
      category: "beach",
    },
    {
      title: "Greek Island Hopper — Athens to Mykonos",
      slug: "greek-island-hopper-athens-mykonos",
      description:
        "A sun-soaked odyssey through the Aegean — explore the Acropolis, cruise to volcanic Santorini, party on Mykonos, and discover hidden coves on lesser-known Naxos and Paros.",
      destination: "Santorini",
      country: "Greece",
      price: 2199,
      duration: 10,
      maxGroupSize: 12,
      difficulty: "easy",
      coverImage: IMG("santorini-caldera-view"),
      images: [IMG("santorini-white-buildings"), IMG("greece-athens-acropolis"), IMG("mykonos-windmills")],
      highlights: [
        "Acropolis and Parthenon guided tour",
        "Santorini caldera cruise with hot springs",
        "Mykonos windmills and Little Venice",
        "Naxos marble villages and ancient Portara",
        "Greek wine and seafood tasting throughout",
      ],
      itinerary: [
        { day: 1, title: "Athens Arrival", description: "Transfer to Plaka hotel, evening walk through the historic centre, Greek meze dinner." },
        { day: 2, title: "Athens Highlights", description: "Acropolis and Parthenon, National Archaeological Museum, Monastiraki flea market." },
        { day: 3, title: "Ferry to Naxos", description: "Morning ferry to Naxos, visit the Portara gateway, afternoon at Agios Prokopios beach." },
        { day: 4, title: "Naxos Villages", description: "Mountain villages of Apeiranthos, marble workshops, local cheese and wine tasting." },
        { day: 5, title: "Paros", description: "Short ferry to Paros, wander Parikia old town, sunset at Naoussa harbour." },
        { day: 6, title: "Santorini", description: "Ferry to Santorini, caldera-view hotel check-in, Oia sunset walk." },
        { day: 7, title: "Santorini Full Day", description: "Caldera sailing cruise, volcanic hot springs swim, Akrotiri ruins, wine tasting at sunset." },
        { day: 8, title: "Mykonos", description: "Ferry to Mykonos, Little Venice, windmills, free afternoon at Paradise Beach." },
        { day: 9, title: "Mykonos Leisure", description: "Delos Island archaeology day trip, evening in Mykonos Town, farewell dinner." },
        { day: 10, title: "Departure", description: "Morning ferry to Athens or direct Mykonos flight departure." },
      ],
      included: ["10 nights (mix of boutique hotels and villas)", "Daily breakfast + 4 dinners", "All inter-island ferry tickets", "Acropolis and Delos guided tours", "Santorini sailing cruise", "Wine and food tastings"],
      notIncluded: ["International flights to/from Athens", "Travel insurance", "Lunches", "Optional nightlife", "Personal expenses"],
      availability: slots(12),
      averageRating: 4.9,
      reviewCount: 64,
      featured: false,
      category: "beach",
    },
    {
      title: "Iceland Winter Wonderland",
      slug: "iceland-winter-wonderland",
      description:
        "Experience Iceland in its most dramatic season — frozen waterfalls, glittering ice caves inside Vatnajökull, snow-covered lava fields, and the best aurora conditions of the year.",
      destination: "Reykjavik",
      country: "Iceland",
      price: 2699,
      duration: 6,
      maxGroupSize: 8,
      difficulty: "moderate",
      coverImage: IMG("iceland-glacier"),
      images: [IMG("iceland-ice-cave"), IMG("iceland-northern-lights"), IMG("iceland-waterfall")],
      highlights: [
        "Natural ice cave tour inside Vatnajökull glacier",
        "Northern lights hunting every night",
        "Snowmobile across the glacier",
        "Frozen Skógafoss and Seljalandsfoss waterfalls",
        "Secret Lagoon geothermal pool",
      ],
      itinerary: [
        { day: 1, title: "Arrival in Reykjavik", description: "Transfer from Keflavik, cosy Reykjavik exploration, first northern lights hunt by minibus." },
        { day: 2, title: "Golden Circle Winter", description: "Þingvellir under snow, erupting Geysir, frozen Gullfoss waterfall, Secret Lagoon soak." },
        { day: 3, title: "South Coast Ice", description: "Frozen Skógafoss and Seljalandsfoss, black Reynisfjara beach, Vík village, northern lights." },
        { day: 4, title: "Glacier Lagoon", description: "Jökulsárlón — icebergs frozen in place, Diamond Beach ice sculptures, glacier walk." },
        { day: 5, title: "Ice Cave & Snowmobile", description: "Natural ice cave expedition inside Vatnajökull, snowmobile tour across the glacier surface." },
        { day: 6, title: "Departure", description: "Final aurora chance at dawn if clear skies, transfer to Keflavik airport." },
      ],
      included: ["6 nights 4★ hotels", "Daily breakfast + 3 dinners", "Natural ice cave tour", "Snowmobile excursion", "Northern lights hunts (every night)", "Secret Lagoon admission", "Private minibus transport"],
      notIncluded: ["International flights", "Travel insurance", "Dinners on days 4–5", "Personal expenses", "Tips"],
      availability: slots(8),
      averageRating: 4.8,
      reviewCount: 51,
      featured: false,
      category: "adventure",
    },
  ]);

  // suppress unused variable warnings — destinations used for clarity
  void [bali, paris, machu, serengeti, santorini, iceland, tokyo, amalfi, marrakech, phuket];

  res.json({ message: "Database seeded successfully", tours: 14, destinations: 10 });
});

export { router as seedRouter };
